#! /bin/bash
#SBATCH --job-name=rope_pct_pythia_1b
#SBATCH --output=logs/rope_pct_pythia_1b-%j.out
#SBATCH --time=15:30:00
#SBATCH --gres=gpu:8
#SBATCH --nodes=4
#SBATCH --cpus-per-task=90
#SBATCH --ntasks-per-node=1
#SBATCH --mem=0                
#SBATCH --requeue

# --- Load necessary modules ---
module load python-waterboa
module load apptainer
module load gcc openmpi

# --- Set up directories and container image ---
export SINGULARITY_TMPDIR="/dais/fs/scratch/afkhan/Artifacts/TEMP" # [Replace with your desired temp directory]
export CONTAINER_IMAGE=/dais/fs/scratch/afkhan/Artifacts/hubble-gpt-neox_2e3a600.sif # [Replace with your container image path]

# Only pull once (skip if already pulled)
if [ ! -f "$CONTAINER_IMAGE" ]; then
    echo "Container image not found. Pulling..."
    apptainer pull docker://ghcr.io/ameyagodbole/hubble-gpt-neox:2e3a600
fi

# --- Set up distributed environment variables ---
export HOSTNAMES=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
export MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_PORT=30001
# Use the robust Slurm variable for node count
export COUNT_NODE=$SLURM_NNODES

echo "JOB ID: $SLURM_JOBID"
echo "NODES: $COUNT_NODE"
echo "HOSTNAMES: $HOSTNAMES"
echo "MASTER_ADDR: $MASTER_ADDR"
echo "MASTER_PORT: $MASTER_PORT"

# --- Create DeepSpeed hostfile ---
# This script should generate the hostfile using the SLURM_JOBID
bash /write_hostfile.sh # [Ensure this path is correct]
# Tell DeepSpeed where to find our generated hostfile
export DLTS_HOSTFILE=hostfiles/hosts_$SLURM_JOBID # [Ensure this path matches the one generated by write_hostfile.sh]
 
TRITON_CACHE_DIR="TRITON_TEMP" # [Replace with your desired Triton cache directory]

# --- Set WANDB API Key ---
export WANDB_API_KEY="" # [Set your WANDB API key here or ensure it's set in your environment]

# --- Execute the distributed training job using srun ---
# Ensure the bind path is correct and that the training script and config files are in the expected locations within the container
srun -l apptainer exec --nv --bind /dais/fs/scratch/afkhan:/dais/fs/scratch/afkhan $CONTAINER_IMAGE \ 
  bash -c '
    set -ex # Exit on error and print commands

    # --- Environment setup inside the container ---
    # <<< MODIFIED: Create a unique cache directory for each job run >>>
    export TRITON_CACHE_DIR="/tmp/TRITON_TEMP_$SLURM_JOBID"
    # <<< ADDED: Ensure the unique cache directory exists >>>
    mkdir -p $TRITON_CACHE_DIR
    export OMP_NUM_THREADS=10

    # <<< FIX: Map Slurm variables to standard distributed training variables >>>
    export RANK=$SLURM_PROCID
    export WORLD_SIZE=$SLURM_NTASKS
    # <<< END FIX >>>

    # --- Log environment for debugging ---
    echo "--------------------------------------------------"
    echo "Node ID: $SLURM_NODEID | Rank: $RANK | World Size: $WORLD_SIZE"
    echo "MASTER_ADDR: $MASTER_ADDR | MASTER_PORT: $MASTER_PORT"
    echo "DLTS_HOSTFILE: $DLTS_HOSTFILE"
    echo "WANDB API Key is set." # Avoid printing the key to logs
    echo "--------------------------------------------------"

    pip install --user ninja
    
    # Optional: Display installed packages
    # pip freeze --all
    
    # --- Run the training script ---
    cd /dais/fs/scratch/afkhan/hubble-gpt-neox
    
    # Replace the path to your training script and config files as needed
    python deepy_simple.py train.py \
      src_config_fw.yml \
      local_setup_fw.yml
'
